steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: '80b8cfc9trial'
      space: 'dev'
      credentialsId: 'CF-jenkins-credentials-id'

  tmsUpload:
    credentialsId: tms_secret_id
    nodeName: uat
    verbose: true
    #stashContent: '/var/jenkins_home/workspace/P1_1_REST_persist_in_Memory@2'
    #mtaPath: com.sap.piper.node.hello.world.mtar

stages:
  Release:
    tmsUpload: true
